# Basics of Linear Algebra Workshop

## Review of Essential Matrix Operations

In [ ]:
# Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python.
# NumPy is the fundamental package for scientific computing in Python.
# SymPy is a Python library for symbolic mathematics.

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import sympy as sypy

### Matrix Addition
Matrix addition is performed element-wise between two matrices of the **same shape**.

For matrices $A$ and $B$:
$$A = \begin{bmatrix}
1 & 6 \\
5 & 2
\end{bmatrix}, \quad
B = \begin{bmatrix}
3 & -1 \\
2 & 4
\end{bmatrix}$$

$$C = A + B = \begin{bmatrix}
1+3 & 6+(-1) \\
5+2 & 2+4
\end{bmatrix} = \begin{bmatrix}
4 & 5 \\
7 & 6
\end{bmatrix}$$

More generally, for two matrices $A$ and $B$ of the same dimensions $m \times n$, the sum $C = A + B$ is defined as:

$$C_{ij} = A_{ij} + B_{ij}$$

for all $i = 1, \ldots, m$ and $j = 1, \ldots, n$.

In [ ]:
# Define the matrices A and B
A = np.array([[1, 6],
              [5, 2],])

B = np.array([[3, -1],
              [2, 4]])

print(f"Matrix A:\n{A}\n")
print(f"Matrix B:\n{B}\n")

Matrix A:
[[1 6]
 [5 2]]

Matrix B:
[[ 3 -1]
 [ 2  4]]



In [ ]:
# Perform matrix addition
C = A + B
print(f"Matrix C (A + B):\n{C}")

Matrix C (A + B):
[[4 5]
 [7 6]]


### Matrix Multiplication

Matrix multiplication is performed between two matrices where the number of columns in the first matrix equals the number of rows in the second matrix.

For matrices $A$ and $B$:

$$A = \begin{bmatrix}
1 & 6 \\
5 & 2
\end{bmatrix}, \quad
B = \begin{bmatrix}
3 & -1 \\
2 & 4
\end{bmatrix}$$

Their product $C = A \times B$ is:

$$C = A \times B = \begin{bmatrix}
(1 \times 3 + 6 \times 2) & (1 \times (-1) + 6 \times 4) \\
(5 \times 3 + 2 \times 2) & (5 \times (-1) + 2 \times 4)
\end{bmatrix} = \begin{bmatrix}
15 & 23 \\
19 & 3
\end{bmatrix}$$

More generally, for two matrices $A$ (m × n) and $B$ (n × p), the product $C = A \times B$ (m × p) is defined as:

$$C_{ij} = \sum_{k=1}^n A_{ik} \times B_{kj}$$
for all $i = 1, \ldots, m$ and $j = 1, \ldots, p$.

Now, let's implement this in Python:

In [ ]:
# Define the matrices A and B
A = np.array([[1, 6],
              [5, 2]])

B = np.array([[3, -1],
              [2, 4]])

print(f"Matrix A:\n{A}\n")
print(f"Matrix B:\n{B}\n")

# Perform matrix multiplication
C = np.dot(A, B)
print(f"Matrix C (AxB):\n{C}")

Matrix A:
[[1 6]
 [5 2]]

Matrix B:
[[ 3 -1]
 [ 2  4]]

Matrix C (AxB):
[[15 23]
 [19  3]]


### The Determinant

The determinant is a scalar value that can be computed from the elements of a square matrix. It has many important applications in linear algebra.

For a 3x3 matrix $A$:
$$A = \begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix}$$

The determinant can be calculated using the Laplace expansion along the first row:

$$det(A) = a(ei-fh) - b(di-fg) + c(dh-eg)$$

**Note:**
1. |det(A)| > 1 means the transformation expands the area/volume
2. |det(A)| < 1 means the transformation contracts the area/volume
3. |det(A)| = 1 means the transformation preserves the area/volume

For our example, let's use the matrix:
$$A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 0
\end{bmatrix}$$

In [ ]:
# Define the 3x3 matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 0]])

print(f"Matrix A:\n{A}\n")

# Compute the determinant using NumPy
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

# What does determinant of 0 mean?

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 0]]

Determinant of A: 27.0


### Gaussian Elimination

Let's solve the following system of linear equations using Gaussian elimination:

$$
\begin{cases}
2x + 3y = 8 \\
4x + 5y = 14
\end{cases}
$$

#### Step 1: Create the augmented matrix

First, we write the system as an augmented matrix:

$$
\begin{bmatrix}
2 & 3 & | & 8 \\
4 & 5 & | & 14
\end{bmatrix}
$$

#### Step 2: Eliminate the variable in the lower-left corner

We'll multiply the first row by -2 and add it to the second row:

$$
\begin{aligned}
R_2 &= R_2 + (-2)R_1 \\
&= \begin{bmatrix}4 & 5 & | & 14\end{bmatrix} + (-2)\begin{bmatrix}2 & 3 & | & 8\end{bmatrix} \\
&= \begin{bmatrix}0 & -1 & | & -2\end{bmatrix}
\end{aligned}
$$

Now our matrix looks like this:

$$
\begin{bmatrix}
2 & 3 & | & 8 \\
0 & -1 & | & -2
\end{bmatrix}
$$

#### Step 3: Back-substitution

From the second row, we can find y:

$$
-y = -2 \implies y = 2
$$

Substituting this into the first equation:

$$
\begin{aligned}
2x + 3(2) &= 8 \\
2x + 6 &= 8 \\
2x &= 2 \\
x &= 1
\end{aligned}
$$

#### Solution

Therefore, the unique solution to the system is:

$$
x = 1, \quad y = 2
$$

## Eigenvalues & Eigenvectors

Eigenvalues and eigenvectors are fundamental concepts in linear algebra that help us understand the behavior of linear transformations and matrices. Eigenvalues and eigenvectors have countless highly impactful applications, including:

**Definition:** Eigenvectors are special vectors that, when transformed by a matrix, only change in scale (stretched or compressed) but not in direction. The corresponding scaling factors are called eigenvalues.

* **Google's PageRank algorithm (early versions):**
  * Used the largest eigenvector of the internet's graph to rank web pages.
* **Data Compression:**
  * Useful when the number of features is much larger than the number of samples.
  * Ex: User recommendation system.
* **Dimensionality Reduction:**
  * Useful when the number of samples is much larger than the number of features.
  * Ex: Seasonality of time series.
* **Special Relativity and the Lorentz Transform:**
  * "Light is an eigenvector of the Lorentz transform." - Einstein

**And SO much more!**

In this notebook, we'll explore the mathematical foundations, calculation, and common operations of eigenvalues and eigenvectors, along with a visual example. This will give you a foundation that applies in countless situations whether it's visualizing data or extracting its most essential features!

### Mathematical Notation

**Definition:** An eigenvector of a matrix is a non-zero vector that, when multiplied by the matrix, results in a scalar multiple of itself. The scalar value by which the eigenvector is scaled is called the eigenvalue associated with that eigenvector.

In mathematical notation, we can represent this as follows:

Let $A$ be a square matrix and $\vec{v}$ be a non-zero vector. If there exists a scalar $\lambda$ (the eigenvalue) such that:

\begin{equation}
A \cdot \vec{v} = \lambda \cdot \vec{v}
\end{equation}

then $v$ is an *eigenvector* of the matrix $A$ with the corresponding *eigenvalue* $\lambda$.

**How to solve for eigenvectors / eigenvalues:**

Given the matrix $A$, we want to find the values for $\lambda$ and the vector $v$ that satisfy the equation $A \cdot \vec{v} = \lambda \cdot \vec{v}$.

1. We can rewrite $\lambda \cdot \vec{v}$ as a matrix multiplication:
  
  $\lambda \cdot \vec{v} = \lambda \cdot I \cdot \vec{v}$
  
  where $I$ is the identity matrix with the same dimensions as $A$. Now, we can factor out $\lambda \cdot I$:

  $A \cdot \vec{v} = \lambda \cdot I \cdot \vec{v}$

2. Subtracting $\lambda \cdot I \cdot \vec{v}$ from both sides, we get the standard eigenvalue - eigenvector equation:

  $(A - \lambda \cdot I) \cdot \vec{v} = 0$

3. Let's consider a 3x3 matrix $A$:

  $$A = \begin{bmatrix}
  a_{11} & a_{12} & a_{13} \\
  a_{21} & a_{22} & a_{23} \\
  a_{31} & a_{32} & a_{33}
  \end{bmatrix}$$

  The identity matrix $I$ for a 3x3 matrix is:

  $$I = \begin{bmatrix}
  1 & 0 & 0 \\
  0 & 1 & 0 \\
  0 & 0 & 1
  \end{bmatrix}$$

  Now, the matrix $A - \lambda \cdot I$ looks like:

  $$A - \lambda \cdot I = \begin{bmatrix}
  a_{11} & a_{12} & a_{13} \\
  a_{21} & a_{22} & a_{23} \\
  a_{31} & a_{32} & a_{33}
  \end{bmatrix} - \lambda \cdot \begin{bmatrix}
  1 & 0 & 0 \\
  0 & 1 & 0 \\
  0 & 0 & 1
  \end{bmatrix}$$

  Performing the matrix addition math, we get:

  $$A - \lambda \cdot I = \begin{bmatrix}
  a_{11} - \lambda & a_{12} & a_{13} \\
  a_{21} & a_{22} - \lambda & a_{23} \\
  a_{31} & a_{32} & a_{33} - \lambda
  \end{bmatrix}$$

  \

4. We are looking for a non-zero vector $\vec{v}$ such that $(A - \lambda \cdot I) \cdot \vec{v} = 0$. To find non-trivial solutions for $\vec{v}$, we introduce the determinant.

5. The determinant of a square matrix is a scalar value that can be computed from the entries of the matrix. For the equation $(A - \lambda \cdot I) \cdot \vec{v} = 0$ to have non-zero solutions for $\vec{v}$, the determinant of $A - \lambda \cdot I$ must be equal to zero:

  $\det(A - \lambda \cdot I) = 0$.
  
  This equation is called the characteristic equation of the matrix $A$.

### Working with Eigenvalues and Eigenvectors using Python

  $$A = \begin{bmatrix}
  1 & 2 & 1 \\
  6 & -1 & 0 \\
  -1 & -2 & -1
  \end{bmatrix}$$

First: Set up the characteristic equation.
$$det(A - \lambda I) = 0$$

$$det(\begin{bmatrix}
  1 & 2 & 1 \\
  6 & -1 & 0 \\
  -1 & -2 & -1
  \end{bmatrix} -
  \begin{bmatrix}
  \lambda & 0 & 0 \\
  0 & \lambda & 0 \\
  0 & 0 & \lambda
  \end{bmatrix}) = 0$$

$$det(\begin{bmatrix}
  1-\lambda & 2 & 1 \\
  6 & -1-\lambda & 0 \\
  -1 & -2 & -1-\lambda
  \end{bmatrix}) = 0$$

In [ ]:
# Create the characteristic equation
A = sypy.Matrix([[1, 2, 1],
               [6, -1, 0],
               [-1, -2, -1]])

Expand the determinant and simplify.

\begin{align*}
0 &= det(\begin{bmatrix}
1-\lambda & 2 & 1 \\
6 & -1-\lambda & 0 \\
-1 & -2 & -1-\lambda
\end{bmatrix}) \\
&= (1-\lambda) det(\begin{bmatrix}
-1-\lambda & 0 \\
-2 & -1-\lambda
\end{bmatrix}) -
(2) det(\begin{bmatrix}
6 & 0 \\
-1 & -1-\lambda
\end{bmatrix}) +
(1) det(\begin{bmatrix}
6 & -1-\lambda \\
-1 & -2
\end{bmatrix})\\
&= (1-\lambda)((-1-\lambda)^2-0) - (2)(6(-1-\lambda)-0) + (1)(-12 - (-1)(-1-\lambda))\\
&= \lambda^3 + \lambda^2 - 12\lambda
\end{align*}

In [ ]:
# Solve the characteristic equation

We want the determinant to equal zero, so we have:

$$\lambda^3 + \lambda^2 - 12\lambda = 0 \\
-\lambda(\lambda + 4)(\lambda - 3) = 0$$

Solving for the roots, we get:

$$
\lambda_{1} = 0 \\
\lambda_{2} = -4 \\
\lambda_{3} = 3
$$

In [ ]:
# Solve for the eigenvalues

### Solve for Eigenvectors using Gaussian Elimination

For the matrix:

$$A = \begin{bmatrix}
1 & 2 & 1 \\
6 & -1 & 0 \\
-1 & -2 & -1
\end{bmatrix}$$

We'll find the eigenvector for $\lambda = 3$.

Solve $(A - 3I)\vec{v} = 0$:

$$\begin{bmatrix}
-2 & 2 & 1 \\
6 & -4 & 0 \\
-1 & -2 & -4
\end{bmatrix}\begin{bmatrix}
v_1 \\
v_2 \\
v_3
\end{bmatrix} = \begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}$$

An eigenvector corresponding to $\lambda = 3$ is $\vec{v} = \begin{bmatrix} -1 \\ -3/2 \\ 1 \end{bmatrix}$.

In [ ]:
# Calculate the eigenvectors

In [ ]:
# numpy linear algebra library version:

### Visual Interpretation

Let's see a visual example of what's going on. Here's our starting matrix:

$$A =
\begin{bmatrix}
1 & 6 \\
5 & 2
\end{bmatrix}$$

Solving for the characteristic equation $det(A - \lambda I)=0$ using Python:

In [ ]:
A = sypy.Matrix([[1, 6],
               [5, 2]])

# Solve for the eigenvalues and eigenvectors

#### Using Matplotlib to Visualize Transformation

In [ ]:
# Create a new figure and axis with a size of 8 inches by 8 inches
fig, ax = plt.subplots(figsize=(8, 8))

# Define an array of arrow coordinates and components
arrows = np.array([[[0, 0, 1, 1]],
                   [[0, 0, 0, 1]],
                   [[0, 0, -6/5, 1]]])

# Define a list of colors for the arrows
colors = ['darkorange', 'darkgreen', 'skyblue']

# Iterate over each row of the arrows array
for i, arrow in enumerate(arrows):
    # Unpack the coordinates and components of the current arrow
    x, y, u, v = arrow[0]

    # Draw the arrow on the plot
    ax.arrow(x, y, u, v, color=colors[i], width=.08,
             length_includes_head=True,
             head_width=.2,
             head_length=.3,
             overhang=0, zorder=-i)

# Set the limits of the x-axis and y-axis
ax.axis([-3, 3.1, -3.1, 3.1])

# Move the left and bottom spines to the center of the plot
ax.spines['left'].set_position('center')
ax.spines['bottom'].set_position('center')

# Remove the right and top spines
ax.spines['right'].set_color('none')
ax.spines['top'].set_color('none')

# Set the position of the x-axis and y-axis ticks
ax.xaxis.set_ticks_position('bottom')
ax.yaxis.set_ticks_position('left')

# Enable minor ticks on the axes
ax.minorticks_on()

# Add a grid to the plot
ax.grid()

# Display the plot
plt.show()

In [ ]:
# Repeat the steps above
fig, ax = plt.subplots(figsize = (8, 8))
arrows = np.array([ [[0,0,1,1]],
                   [[0,0,0,1]],
                  [[0,0,-6/5,1]]])
colors = ['darkorange','darkgreen','skyblue']
for i, arrow in enumerate(arrows):
    x, y, u, v = arrow[0]

    ax.arrow(x, y, u, v, color=colors[i], width=.08,
             length_includes_head=True,
             head_width=.2,
             head_length=.3,
             overhang=0, zorder=-i)

################################### Eigenspace #################################
x = np.arange(-10, 10.6, .5)
y = x
ax.plot(x, y, lw = 3, color = 'red', alpha = .5, label = 'Eigenspace for $\lambda = 7$')

x = np.arange(-10, 10.6, .5)
y = -5/6*x
ax.plot(x, y, lw = 3, color = 'blue', alpha = .5,  label = 'Eigenspace for $\lambda = -4$')

############################ Legend ###############################

leg = ax.legend(fontsize = 15, loc = 'lower right')
leg.get_frame().set_alpha(0.5)

###################### Axis, Spines, Ticks ##########################
ax.axis([-3, 3.1, -3.1, 3.1])
ax.spines['left'].set_position('center')
ax.spines['right'].set_color('none')
ax.spines['bottom'].set_position('center')
ax.spines['top'].set_color('none')
ax.xaxis.set_ticks_position('bottom')
ax.yaxis.set_ticks_position('left')

ax.minorticks_on()
ax.grid()
plt.show()

In [ ]:
# Repeat the steps to plot the arrows once more, but with transformations
fig, ax = plt.subplots(figsize = (8, 8))
arrows = np.array([ [[0,0,1,1]],
                    [[0,0,-6/5,1]],
                    [[0,0,0,1]], # Add a vector that is not an eigenvector
                    [[0,0,7,7]],
                    [[0,0,24/5,-4]],
                    [[0,0,6,2]]]) # This is the resulting transformed vector
colors = ['darkorange','skyblue','lightgreen','r','b','g']
for i, arrow in enumerate(arrows):
    x, y, u, v = arrow[0]

    ax.arrow(x, y, u, v, color=colors[i], width=.1,
             length_includes_head=True,
             head_width=.3,
             head_length=.3,
             overhang=0, zorder=-i)

################################### Eigenspace #################################
x = np.arange(-10, 10.6, .5)
y = x
ax.plot(x, y, lw = 3, color = 'red', alpha = .3, label = 'Eigenspace for $\lambda = 7$')

x = np.arange(-10, 10.6, .5)
y = -5/6*x
ax.plot(x, y, lw = 3, color = 'blue', alpha = .3,  label = 'Eigenspace for $\lambda = -4$')

######################## Annotation Arrows ################################

style="Simple, tail_width=0.5, head_width=5, head_length=10"
kw = dict(arrowstyle=style, color="k")

a = mpatches.FancyArrowPatch((1,1), (7,7),connectionstyle="arc3,rad=.4", **kw, alpha = .3)
plt.gca().add_patch(a)

a = mpatches.FancyArrowPatch((-6/5,1), (24/5,-4),connectionstyle="arc3,rad=.4", **kw, alpha = .3)
plt.gca().add_patch(a)

############################ Legend ###############################

leg = ax.legend(fontsize = 15, loc = 'lower right')
leg.get_frame().set_alpha(0.5)

###################### Axis, Spines, Ticks ##########################
ax.axis([-10, 10.1, -10.1, 10.1])
ax.spines['left'].set_position('center')
ax.spines['right'].set_color('none')
ax.spines['bottom'].set_position('center')
ax.spines['top'].set_color('none')
ax.xaxis.set_ticks_position('bottom')
ax.yaxis.set_ticks_position('left')

ax.minorticks_on()
ax.grid()
plt.show()

## Resources

1. [3Blue1Brown - Essence of Linear Algebra on YouTube](https://youtu.be/fNk_zzaMoSs?si=XU5aRSySd0VPpMV5)
2. Codecademy!
  1. https://www.codecademy.com/learn/learn-python-3
  2. https://www.codecademy.com/learn/paths/fundamental-math-for-data-science
  3. https://www.codecademy.com/catalog/subject/data-science
  4. https://www.codecademy.com/catalog/subject/machine-learning
  5. https://www.codecademy.com/catalog/subject/artificial-intelligence
  6. https://www.codecademy.com/catalog/subject/data-visualization
3. [Mathematics for Machine Learning - Free PDF](https://mml-book.github.io/)
4. https://medium.com/@israel-miles